import fs from "fs-extra";
const { writeFileSync } = fs;

const createNavigation = (dirDst, navigator) => {
  console.log(`Write ${dirDst}/src/routes/index.ts`);
  const fileContent = `\
// NOTICE: This file is auto-generated by wl-engine.
import navigator from '${navigator}'\n
export default navigator.component;
`;
  writeFileSync(`${dirDst}/src/navigation/index.ts`, fileContent);
};

export default createNavigation;
