import fs from "fs-extra";
const { writeFileSync } = fs;
const createTheme = (dirDst, theme) => {
  console.log(`Write ${dirDst}/src/theme/index.js`);
  const fileContent = `\
// NOTICE: This file is auto-generated by wl-engine.
export { default } from './themes/${theme}';
`;
  writeFileSync(`${dirDst}/src/theme/index.js`, fileContent);
};

export default createTheme;
