import fs from "fs-extra";
const { writeFileSync } = fs;

const createBaseUrl = (dirDst, baseUrl) => {
  console.log(`Write ${dirDst}/src/api/server.js`);
  const fileContent = `\
// NOTICE: This file is auto-generated by wl-engine.
export default '${baseUrl}';
`;
  writeFileSync(`${dirDst}/src/baseUrl.js`, fileContent);
};

export default createBaseUrl;
